### ISSUE TITLE
Building the documentation failed

### ISSUE THREAD

**Issue by Paebbels** [NJDFan/register-maps#1]
I looked at your new documentation at ReadTheDocs.
There is a shield, that can be included in your main `README.md` file, to
* link to the documentation from the GitHub repository website
* show the build status of the documentation.

The Markdown source code is:

```markdown
[![Documentation Status](http://readthedocs.org/projects/register-maps/badge/?version=latest)](http://register-maps.readthedocs.io/en/latest/?badge=latest)
```

It looks like this: [![Documentation Status](http://readthedocs.org/projects/register-maps/badge/?version=latest)](http://register-maps.readthedocs.io/en/latest/?badge=latest)

--------------
**Edit:**

Sorry, you need the ReST markup:

```rst
.. image:: http://readthedocs.org/projects/register-maps/badge/?version=latest
   :target: http://register-maps.readthedocs.io/en/latest/?badge=latest
   :alt: Documentation Status
```

**Comment by NJDFan** [comment]
Fixed.
