### ISSUE TITLE
run error on  __init__.py

### ISSUE THREAD

**Issue by helloworld1983** [NJDFan/register-maps#5]
hello,
     I have installed on Python 3.5/3.7 and compile success. when I run there is an error on __init__.py.how to do

**Comment by NJDFan** [comment]
What platform?  How did you install register-maps?  What was the error?

Please copy and paste error messages directly into your reply.

**Comment by helloworld1983** [comment]
Hello,
    I find the problem,when run the __package__ in util.py is null. I add follow in util.py begin, it's ok now.
if __package__ == '':
    path = os.path.dirname(os.path.dirname(__file__))
    sys.path.insert(0, path) 



zm19830216
 
From: NJDFan
Date: 2019-02-15 02:52
To: NJDFan/register-maps
CC: helloworld1983; Author
Subject: Re: [NJDFan/register-maps] run error on __init__.py (#5)
What platform? How did you install register-maps? What was the error?
Please copy and paste error messages directly into your reply.
―
